// <auto-generated />
using System;
using Dcar.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dcar.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126151836_MudancaIdentityParaUtilizador")]
    partial class MudancaIdentityParaUtilizador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dcar.Models.Administrador", b =>
                {
                    b.Property<int>("IdAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_admin");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAdmin"));

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdAdmin")
                        .HasName("PK__Administ__89472E95AAE53A56");

                    b.ToTable("Administrador", (string)null);
                });

            modelBuilder.Entity("Dcar.Models.Agendum", b =>
                {
                    b.Property<int>("IdAgenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_agenda");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAgenda"));

                    b.Property<DateOnly>("DataAgenda")
                        .HasColumnType("date")
                        .HasColumnName("data_agenda");

                    b.Property<DateTime>("DataVisita")
                        .HasColumnType("datetime")
                        .HasColumnName("data_visita");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("pendente")
                        .HasColumnName("estado");

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int")
                        .HasColumnName("id_anuncio");

                    b.Property<int>("IdComprador")
                        .HasColumnType("int")
                        .HasColumnName("id_comprador");

                    b.HasKey("IdAgenda")
                        .HasName("PK__Agenda__178E6FBB0F73CC22");

                    b.HasIndex("IdAnuncio");

                    b.HasIndex("IdComprador");

                    b.ToTable("Agenda");
                });

            modelBuilder.Entity("Dcar.Models.Anuncio", b =>
                {
                    b.Property<int>("IdAnuncio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_anuncio");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAnuncio"));

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("estado");

                    b.Property<string>("Fotos")
                        .HasColumnType("text")
                        .HasColumnName("fotos");

                    b.Property<int>("IdCarro")
                        .HasColumnType("int")
                        .HasColumnName("id_carro");

                    b.Property<int>("IdVendedor")
                        .HasColumnType("int")
                        .HasColumnName("id_vendedor");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("localizacao");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("preco");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("titulo");

                    b.HasKey("IdAnuncio")
                        .HasName("PK__Anuncio__4AF1EDBB595BBCE8");

                    b.HasIndex("IdVendedor");

                    b.HasIndex(new[] { "IdCarro" }, "UQ_Anuncio_Carro")
                        .IsUnique();

                    b.ToTable("Anuncio", (string)null);
                });

            modelBuilder.Entity("Dcar.Models.Carro", b =>
                {
                    b.Property<int>("IdCarro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_carro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarro"));

                    b.Property<int>("Ano")
                        .HasColumnType("int")
                        .HasColumnName("ano");

                    b.Property<string>("Caixa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("caixa");

                    b.Property<int>("IdCombustivel")
                        .HasColumnType("int")
                        .HasColumnName("id_combustivel");

                    b.Property<int>("IdModelo")
                        .HasColumnType("int")
                        .HasColumnName("id_modelo");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("matricula");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("int")
                        .HasColumnName("quilometragem");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .IsUnicode(false)
                        .HasColumnType("varchar(17)")
                        .HasColumnName("VIN");

                    b.HasKey("IdCarro")
                        .HasName("PK__Carro__D3C318A18E59BD0B");

                    b.HasIndex("IdCombustivel");

                    b.HasIndex("IdModelo");

                    b.HasIndex(new[] { "Matricula" }, "UQ__Carro__30962D151703B4D1")
                        .IsUnique();

                    b.HasIndex(new[] { "Vin" }, "UQ__Carro__C5DF234C60A47882")
                        .IsUnique()
                        .HasFilter("[VIN] IS NOT NULL");

                    b.ToTable("Carro", (string)null);
                });

            modelBuilder.Entity("Dcar.Models.Combustivel", b =>
                {
                    b.Property<int>("IdCombustivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_combustivel");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCombustivel"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.HasKey("IdCombustivel")
                        .HasName("PK__Combusti__59352B78F17ED9EF");

                    b.HasIndex(new[] { "Tipo" }, "UQ__Combusti__E7F95649E2B6424A")
                        .IsUnique();

                    b.ToTable("Combustivel", (string)null);
                });

            modelBuilder.Entity("Dcar.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_compra");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime")
                        .HasColumnName("data");

                    b.Property<string>("EstadoPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado_pagamento");

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int")
                        .HasColumnName("id_anuncio");

                    b.Property<int>("IdComprador")
                        .HasColumnType("int")
                        .HasColumnName("id_comprador");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("preco");

                    b.HasKey("IdCompra")
                        .HasName("PK__Compra__C4BAA604E12282D9");

                    b.HasIndex("IdComprador");

                    b.HasIndex(new[] { "IdAnuncio" }, "UQ_Compra_Anuncio")
                        .IsUnique();

                    b.ToTable("Compra", (string)null);
                });

            modelBuilder.Entity("Dcar.Models.Comprador", b =>
                {
                    b.Property<int>("IdComprador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_comprador");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComprador"));

                    b.Property<string>("Contactos")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("contactos");

                    b.Property<string>("Morada")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("morada");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdComprador")
                        .HasName("PK__Comprado__BE02FD9B7A2D6A54");

                    b.ToTable("Comprador", (string)null);
                });

            modelBuilder.Entity("Dcar.Models.Denuncium", b =>
                {
                    b.Property<int>("IdDenuncia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_denuncia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDenuncia"));

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime")
                        .HasColumnName("data_abertura");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Aberta")
                        .HasColumnName("estado");

                    b.Property<int?>("IdAlvoAnuncio")
                        .HasColumnType("int")
                        .HasColumnName("id_alvo_anuncio");

                    b.Property<string>("IdDenuncianteUser")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id_denunciante_user");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.HasKey("IdDenuncia")
                        .HasName("PK__Denuncia__2BD955A41A1F5F38");

                    b.HasIndex("IdAlvoAnuncio");

                    b.ToTable("Denuncia");
                });

            modelBuilder.Entity("Dcar.Models.Marca", b =>
                {
                    b.Property<int>("IdMarca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarca"));

                    b.Property<string>("NomeMarca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_marca");

                    b.HasKey("IdMarca")
                        .HasName("PK__Marca__7E43E99E9E59784A");

                    b.HasIndex(new[] { "NomeMarca" }, "UQ__Marca__93217C604DFFABE0")
                        .IsUnique();

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("Dcar.Models.Modelo", b =>
                {
                    b.Property<int>("IdModelo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_modelo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModelo"));

                    b.Property<int>("IdMarca")
                        .HasColumnType("int")
                        .HasColumnName("id_marca");

                    b.Property<string>("NomeModelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome_modelo");

                    b.HasKey("IdModelo")
                        .HasName("PK__Modelo__B3BFCFF1367160B2");

                    b.HasIndex("IdMarca");

                    b.HasIndex(new[] { "NomeModelo", "IdMarca" }, "UQ__Modelo__BC48DA93621EF7FF")
                        .IsUnique();

                    b.ToTable("Modelo", (string)null);
                });

            modelBuilder.Entity("Dcar.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_reserva");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("estado");

                    b.Property<int>("IdAnuncio")
                        .HasColumnType("int")
                        .HasColumnName("id_anuncio");

                    b.Property<int>("IdComprador")
                        .HasColumnType("int")
                        .HasColumnName("id_comprador");

                    b.Property<DateOnly?>("PrazoExpiracao")
                        .HasColumnType("date")
                        .HasColumnName("prazo_expiracao");

                    b.HasKey("IdReserva")
                        .HasName("PK__Reserva__423CBE5DEAA43B50");

                    b.HasIndex("IdAnuncio");

                    b.HasIndex("IdComprador");

                    b.ToTable("Reserva", (string)null);
                });

            modelBuilder.Entity("Dcar.Models.Utilizador", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NomeCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Dcar.Models.Vendedor", b =>
                {
                    b.Property<int>("IdVendedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_vendedor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVendedor"));

                    b.Property<string>("Contactos")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("contactos");

                    b.Property<string>("EstadoAprovacao")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("pendente")
                        .HasColumnName("estado_aprovacao");

                    b.Property<string>("Morada")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("morada");

                    b.Property<string>("Nif")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("NIF");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Tipo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tipo");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("IdVendedor")
                        .HasName("PK__Vendedor__00930308EDA20D20");

                    b.ToTable("Vendedor", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Dcar.Models.Agendum", b =>
                {
                    b.HasOne("Dcar.Models.Anuncio", "IdAnuncioNavigation")
                        .WithMany("Agenda")
                        .HasForeignKey("IdAnuncio")
                        .IsRequired()
                        .HasConstraintName("FK__Agenda__id_anunc__02FC7413");

                    b.HasOne("Dcar.Models.Comprador", "IdCompradorNavigation")
                        .WithMany("Agenda")
                        .HasForeignKey("IdComprador")
                        .IsRequired()
                        .HasConstraintName("FK__Agenda__id_compr__02084FDA");

                    b.Navigation("IdAnuncioNavigation");

                    b.Navigation("IdCompradorNavigation");
                });

            modelBuilder.Entity("Dcar.Models.Anuncio", b =>
                {
                    b.HasOne("Dcar.Models.Carro", "IdCarroNavigation")
                        .WithOne("Anuncio")
                        .HasForeignKey("Dcar.Models.Anuncio", "IdCarro")
                        .IsRequired()
                        .HasConstraintName("FK__Anuncio__id_carr__787EE5A0");

                    b.HasOne("Dcar.Models.Vendedor", "IdVendedorNavigation")
                        .WithMany("Anuncios")
                        .HasForeignKey("IdVendedor")
                        .IsRequired()
                        .HasConstraintName("FK__Anuncio__id_vend__778AC167");

                    b.Navigation("IdCarroNavigation");

                    b.Navigation("IdVendedorNavigation");
                });

            modelBuilder.Entity("Dcar.Models.Carro", b =>
                {
                    b.HasOne("Dcar.Models.Combustivel", "IdCombustivelNavigation")
                        .WithMany("Carros")
                        .HasForeignKey("IdCombustivel")
                        .IsRequired()
                        .HasConstraintName("FK__Carro__id_combus__693CA210");

                    b.HasOne("Dcar.Models.Modelo", "IdModeloNavigation")
                        .WithMany("Carros")
                        .HasForeignKey("IdModelo")
                        .IsRequired()
                        .HasConstraintName("FK__Carro__id_modelo__68487DD7");

                    b.Navigation("IdCombustivelNavigation");

                    b.Navigation("IdModeloNavigation");
                });

            modelBuilder.Entity("Dcar.Models.Compra", b =>
                {
                    b.HasOne("Dcar.Models.Anuncio", "IdAnuncioNavigation")
                        .WithOne("Compra")
                        .HasForeignKey("Dcar.Models.Compra", "IdAnuncio")
                        .IsRequired()
                        .HasConstraintName("FK__Compra__id_anunc__08B54D69");

                    b.HasOne("Dcar.Models.Comprador", "IdCompradorNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("IdComprador")
                        .IsRequired()
                        .HasConstraintName("FK__Compra__id_compr__07C12930");

                    b.Navigation("IdAnuncioNavigation");

                    b.Navigation("IdCompradorNavigation");
                });

            modelBuilder.Entity("Dcar.Models.Denuncium", b =>
                {
                    b.HasOne("Dcar.Models.Anuncio", "IdAlvoAnuncioNavigation")
                        .WithMany("Denuncia")
                        .HasForeignKey("IdAlvoAnuncio")
                        .HasConstraintName("FK__Denuncia__id_alv__0E6E26BF");

                    b.Navigation("IdAlvoAnuncioNavigation");
                });

            modelBuilder.Entity("Dcar.Models.Modelo", b =>
                {
                    b.HasOne("Dcar.Models.Marca", "IdMarcaNavigation")
                        .WithMany("Modelos")
                        .HasForeignKey("IdMarca")
                        .IsRequired()
                        .HasConstraintName("FK__Modelo__id_marca__6383C8BA");

                    b.Navigation("IdMarcaNavigation");
                });

            modelBuilder.Entity("Dcar.Models.Reserva", b =>
                {
                    b.HasOne("Dcar.Models.Anuncio", "IdAnuncioNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdAnuncio")
                        .IsRequired()
                        .HasConstraintName("FK__Reserva__id_anun__7C4F7684");

                    b.HasOne("Dcar.Models.Comprador", "IdCompradorNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdComprador")
                        .IsRequired()
                        .HasConstraintName("FK__Reserva__id_comp__7D439ABD");

                    b.Navigation("IdAnuncioNavigation");

                    b.Navigation("IdCompradorNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Dcar.Models.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Dcar.Models.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dcar.Models.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Dcar.Models.Utilizador", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dcar.Models.Anuncio", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("Compra");

                    b.Navigation("Denuncia");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Dcar.Models.Carro", b =>
                {
                    b.Navigation("Anuncio");
                });

            modelBuilder.Entity("Dcar.Models.Combustivel", b =>
                {
                    b.Navigation("Carros");
                });

            modelBuilder.Entity("Dcar.Models.Comprador", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("Compras");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Dcar.Models.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("Dcar.Models.Modelo", b =>
                {
                    b.Navigation("Carros");
                });

            modelBuilder.Entity("Dcar.Models.Vendedor", b =>
                {
                    b.Navigation("Anuncios");
                });
#pragma warning restore 612, 618
        }
    }
}
